// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yipfuyyuytteficycntz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcGZ1eXl1eXR0ZWZpY3ljbnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzMzNDQsImV4cCI6MjA3MjY0OTM0NH0.EkAoBtnmeP29lzjc3kWpm08YbY980chZYOcTpx9sRNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});